name: manipulator5d

defaults: #all defaults can be overwritten per node
  eds_pkg: birl_module_canopen
  eds_file: "config/birl_copley.dcf" #CopleyAmp2.eds" #birl_copley.dcf"   #Schunk_0_63.dcf"  
  encoder_resolution: 4096
    
  # the below part of the defaults section is optional
    # canopen_chain_node settings ..
  motor_allocator: canopen::Motor402::Allocator # select allocator for motor layer
  motor_layer: #settings passed to motor layer (plugin-specific)
    switching_state: 5 # (Operation_Enable), state for mode switching
  pos_to_device: "rint(rad2deg(pos)*4096*480/360)" # rad -> mdeg * resolution of encoder * reduction ratio / 360 degree
  pos_from_device: "deg2rad(obj6064)*360/480/4096" # actual position [count] -> rad
  vel_to_device: "rint(rad2deg(vel)*4096*480/360*10)" # rad/s -> mdeg/s
  vel_from_device: "deg2rad(obj606C)*360/10/480/4096" # actual velocity [0.1count/s] -> rad/s
  eff_to_device: "rint(eff)" # just round to integer
  eff_from_device: "0" # unset!! effort on motor!
  
  dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
#    "6081": "0x90000" # velocity that the trajectory generator attempts to achieve when in position profile mode.
#    "1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127
#    "1017": "1000" # heartbeat producer, set the node to repoduce heart beat signal every second
    "60c0": "0x0000" # map Interpolation submode 0:Linear interpolation with constant time. -1:varible time -2:PVT
    "1600sub0": "1"
    "1600sub1": "0x60400010" # map Control Word to RPDO1
    "1601sub0": "1"
    "1605sub1": "0x60600008" # map 0x6060(mode of operation) to RPDO6
    "1602sub0": "1"
    "1602sub1": "0x607a0020" # map 607a Target Position to RPDO3
    "1603sub0": "1"
    "1603sub1": "0x60ff0020" # map 607a Target Velocity to RPDO4
    "1604sub0": "1"
    "1604sub1": "0x60710010" # map 607a Target torque to RPDO5
    "1605sub0": "1"
    "1601sub1": "0x60c10120" # map 60c1sub1(position for PVT mode) to RPDO2
    "1606sub0": "1"
    "1606sub1": "0x60c10208" # map 60c1sub2(time for PVT mode) to RPDO7
    "1607sub0": "1"
    "1607sub1": "0x60c10320" # map 60c1sub3(velocity for PVT mode) to RPDO8
   
    
#    "1a00sub0": "1"
#    "1a00sub1": "0x60410010" # map Status Word to TPDO1
#    "1a01sub0": "1"
#    "1a01sub1": "0x60610008" # map Display mode of operation to TPDO2   
#    "1a02sub0": "2"
#    "1a02sub1": "0x60640020" # map actual position to TPDO3
#    "1a03sub0": "2"
#    "1a03sub1": "0x606C0020" # map actual velocity to TPDO4
#    "1a04sub0": "1"
#    "1a04sub1": "0x60770010" # map actual torque to TPDO5
#    "1a05sub0": "0" 
##    "1a05sub1": " " # TPDO6
#    "1a06sub0": "1"
#    "1a06sub1": "0x60FD0020" # map digital input to TPDO7
    
    
        
#pos_unit_factor: 1000000.0
#vel_unit_factor: 1000000.0

    
nodes:
  - name: I1_Joint
    id: 1
    pos_to_device: "rint(rad2deg(pos)*4096*457/360)" # rad -> mdeg * resolution of encoder * reduction ratio / 360 degree
    pos_from_device: "deg2rad(obj6064)*360/457/4096" # actual position [count] -> rad
    vel_to_device: "rint(rad2deg(vel)*4096*457/360)" # rad/s -> mdeg/s
    vel_from_device: "deg2rad(obj606C)*360/457/4096" # actual velocity [count/s] -> rad/s
    eff_to_device: "rint(eff)" # just round to integer
    eff_from_device: "0" # unset!! effort on motor!
    #publish: ["1003sub0!"] # For debugging or for simple CANopen interfaces. it blocks the control loop
    #publish: ["6064!"]  #actual position_actual_value
    encoder_resolution: 4096
    
  - name: T2_Joint
    id: 2
    #publish: ["1003sub0!"] # For debugging or for simple CANopen interfaces. it blocks the control loop
    #publish: ["6064!"]  #actual position_actual_value
    
  - name: T3_Joint
    id: 3
    #publish: ["1003sub0!"] # For debugging or for simple CANopen interfaces. it blocks the control loop
    #publish: ["6064!"]  #actual position_actual_value


  - name: i4_Joint
    id: 4
    pos_to_device: "rint(rad2deg(pos)*4096*188.24/360)" # rad -> mdeg * resolution of encoder * reduction ratio / 360 degree
    pos_from_device: "deg2rad(obj6064)*360/188.24/4096" # actual position [count] -> rad
    vel_to_device: "rint(rad2deg(vel)*4096*188.24/360)" # rad/s -> mdeg/s
    vel_from_device: "deg2rad(obj606C)*360/188.24/4096" # actual velocity [count/s] -> rad/s
    eff_to_device: "rint(eff)" # just round to integer
    eff_from_device: "0" # unset!! effort on motor!
    #publish: ["1003sub0!"] # For debugging or for simple CANopen interfaces. it blocks the control loop
    #publish: ["6064!"]  #actual position_actual_value
    encoder_resolution: 4096

  - name: t5_Joint
    id: 5
    pos_to_device: "rint(rad2deg(pos)*4096*200/360)" # rad -> mdeg * resolution of encoder * reduction ratio / 360 degree
    pos_from_device: "deg2rad(obj6064)*360/200/4096" # actual position [count] -> rad
    vel_to_device: "rint(rad2deg(vel)*4096*200/360)" # rad/s -> mdeg/s
    vel_from_device: "deg2rad(obj606C)*360/200/4096" # actual velocity [count/s] -> rad/s
    eff_to_device: "rint(eff)" # just round to integer
    eff_from_device: "0" # unset!! effort on motor!
    #publish: ["1003sub0!"] # For debugging or for simple CANopen interfaces. it blocks the control loop
    #publish: ["6064!"]  #actual position_actual_value
    encoder_resolution: 4096
